### ISSUE TITLE
Hekili.GetQueue().Primary[1].actionName

### ISSUE THREAD

**Issue by replikatoren** [henke164/wow-cyborg#11]
Cant call that, why? Trying your pixelbot and cant figure it out

**Comment by henke164** [comment]
Hello. To use rotations that use Hekili, you will need to install the Hekili Addon. Then you need to modify / add the following in Hekili.lua:

You can put this function around row 131:

function Hekili:GetQueue()
  return ns.queue;
end

**Comment by henke164** [comment]
> Hello. To use rotations that use Hekili, you will need to install the Hekili Addon. Then you need to modify / add the following in Hekili.lua:
> 
> You can put this function around row 131:
> 
> function Hekili:GetQueue() return ns.queue; end


Hello. To use rotations that use Hekili, you will need to install the Hekili Addon. Then you need to modify / add the following in Hekili.lua:

You can put this function around row 131:

function Hekili:GetQueue()
return ns.queue;
end
